### ISSUE TITLE
remaining structural members

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/Lake_Kegonsa_Home#13]
Hi @bausk 

Can you size remaining members?  The following PDFs show their locations...
https://github.com/OpeningDesign/Lake_Kegonsa_Home/commit/dd375a52e1e2aac0b11baa330caaf871bec674b7

Not that alot has changed, but i also uploaded a new IFC file here, if you need it:
https://github.com/OpeningDesign/Lake_Kegonsa_Home/commit/e3574aeb474d02007898deb494126172e8806c05

They are starting to frame this week, so if you could get to these this week, that would ideal.

Thanks, Ryan

**Comment by bausk** [comment]
Ryan, yes, absolutely, will do them asap (tomorrow is Orthodox Christmas
though so please take that into account)

On Tue, Jan 6, 2015 at 7:07 PM, Ryan Schultz <notifications@github.com>
wrote:

> Hi @bausk <https://github.com/bausk>
>
> Can you size remaining members? The following PDFs show their locations...
> dd375a5
> <https://github.com/OpeningDesign/Lake_Kegonsa_Home/commit/dd375a52e1e2aac0b11baa330caaf871bec674b7>
>
> Not that alot has changed, but i also uploaded a new IFC file here, if you
> need it:
> e3574ae
> <https://github.com/OpeningDesign/Lake_Kegonsa_Home/commit/e3574aeb474d02007898deb494126172e8806c05>
>
> They are starting to frame this week, so if you could get to these this
> week, that would ideal.
>
> Thanks, Ryan
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpeningDesign/Lake_Kegonsa_Home/issues/13>.
>



-- 
Alexander Bausk
IT Analyst, Structural engineer
MSc Structural engineering, Ph.C. Engineering
Professional blog at http://writandraw.org

**Comment by theoryshaw** [comment]
Merry Christmas!... my kids would love two Christmases. ;)

For the ridge beam, was thinking it would be an LVL, so it's easier to tie in (nail in) the rafters.

Thanks.

**Comment by bausk** [comment]
Ryan, please see the commit for basement LVLs:
https://github.com/OpeningDesign/Lake_Kegonsa_Home/commit/9a296bc2cb9c8a0ca406ebd9229f019eb4b13b74

I will also upload the ridge beam and accompanying pictures later in the day. Please inform me if we need to work out different sizes, esp. for the 11.25" one along grid (E).

**Comment by bausk** [comment]
Ryan, please see the next commit for ridge beam:
https://github.com/OpeningDesign/Lake_Kegonsa_Home/commit/23a5086f42853d8350ffb516d2bce35e0a61efc2

Results for ridge beam are:
Section: 3½" x 16" OR 5¼" x 14"
This is slightly larger than in current model due to rather large cantilevered length.

**Comment by bausk** [comment]
Ryan, I need a comment on the remaining beam in the roof floor along gridline (H). What is the purpose of that beam? From what I can get from the 3D model, it doesn't seem to support anything.

**Comment by theoryshaw** [comment]
here's that condition... https://www.youtube.com/watch?v=vXK-MJ3R9ZU

It's a unique condition, not sure if there needs to be additional structure there.

**Comment by theoryshaw** [comment]
fyi, those two 2x4 columns are temporary.

**Comment by theoryshaw** [comment]
Discussed solution with @stevenuecke

**Comment by bausk** [comment]
Ryan, an update on this issue: I have reviewed the video and don't see the need to add anything there, as far as can be seen from the available info

**Comment by theoryshaw** [comment]
Alex, @stevenuecke suggested sistering a 2x10 along side that 2x4 ceiling joist and carrying the load down to the steel beam below.
