### ISSUE TITLE
Minimum Suggested Bearing Width at Stone Ledge

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/Lake_Kegonsa_Home#14]
@bausk Alex, would you happen to know the answer to this?...
http://www.eng-tips.com/viewthread.cfm?qid=378539

![2015-01-19 18 00 42](https://cloud.githubusercontent.com/assets/507113/5810578/525835ea-a00e-11e4-8778-aea89ca6f1b2.jpg)

**Comment by bausk** [comment]
Ryan, I would recommend to use the whole width of 4" even if the wall is
non-bearing, is that possible?

On Tue, Jan 20, 2015 at 3:07 AM, Ryan Schultz <notifications@github.com>
wrote:

> @bausk <https://github.com/bausk> Alex, would you happen to know the
> answer to this?...
> http://www.eng-tips.com/viewthread.cfm?qid=378539
>
> [image: 2015-01-19 18 00 42]
> <https://cloud.githubusercontent.com/assets/507113/5810578/525835ea-a00e-11e4-8778-aea89ca6f1b2.jpg>
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpeningDesign/Lake_Kegonsa_Home/issues/14>.
>



-- 
Alexander Bausk
IT Analyst, Structural engineer
MSc Structural engineering, Ph.C. Engineering
Professional blog at http://writandraw.org

**Comment by bausk** [comment]
Otherwise, the codes provide a minimum 2/3 of wythe thickness as a support
condition, that's 2 2/3 " in this case

On Tue, Jan 20, 2015 at 11:00 AM, Alexander Bausk <bauskas@gmail.com> wrote:

> Ryan, I would recommend to use the whole width of 4" even if the wall is
> non-bearing, is that possible?
>
> On Tue, Jan 20, 2015 at 3:07 AM, Ryan Schultz <notifications@github.com>
> wrote:
>
>> @bausk <https://github.com/bausk> Alex, would you happen to know the
>> answer to this?...
>> http://www.eng-tips.com/viewthread.cfm?qid=378539
>>
>> [image: 2015-01-19 18 00 42]
>> <https://cloud.githubusercontent.com/assets/507113/5810578/525835ea-a00e-11e4-8778-aea89ca6f1b2.jpg>
>>
>> --
>> Reply to this email directly or view it on GitHub
>> <https://github.com/OpeningDesign/Lake_Kegonsa_Home/issues/14>.
>>
>
>
>
> --
> Alexander Bausk
> IT Analyst, Structural engineer
> MSc Structural engineering, Ph.C. Engineering
> Professional blog at http://writandraw.org
>



-- 
Alexander Bausk
IT Analyst, Structural engineer
MSc Structural engineering, Ph.C. Engineering
Professional blog at http://writandraw.org

**Comment by theoryshaw** [comment]
Thanks Alex.  Yes, 4" is unattainable in this scenario.
